version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./preinstall/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dev
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go", "models.go"]
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
