swagger: "2.0"
info:
  title: BOTWA API
  description: Breath of the Wild API.
  version: 1.0.0
host: localhost:8080
schemes:
  - https
paths:
  /articles:
    post:
      summary: Create article.
      description: Create an article.
      produces:
        - application/json
      responses:
        201:
          description: Success
    get:
      summary: List articles.
      description: Get all article.
      produces:
        - application/json
      responses:
        200:
          description: Success
  /articles/{article_id}:
    get:
      summary: Read article.
      description: Get article by id.
      produces:
        - application/json
      parameters:
        - name: article_id
          in: path
          description: Id of the article to return
          required: true
          type: integer
      responses:
        200:
          description: Success

